name: Build

on:
  pull_request:
    branches:
      - feature/*
      - develop
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-project-jar
          path: target/*.jar
